### PR TITLE
standardize select rows to be consistent with other rows

### LINKED ISSUE #68: Rows should be identical heights
screen shot 2016-10-25 at 2 35 52 pm
On the "Add Recipe" page, the rows that class="item item-input item-select" should be identical to the rows that are class="item item-input". I believe this would have a better visual experience that different sized rows.

### PR DESCRIPTION
**Pull request by codeavenger07**
Fixes #68 
screen shot 2016-10-25 at 8 58 22 pm

### CODE REVIEW

**Comment by codeavenger07** [comment]
Could you please tag for hacktoberfest? 👍

**Comment by MichaelWashburnJr** [comment]
I can, and did, but you still get the credit for having PRs, even if they aren't labeled with Hacktoberfest :)

**Comment by codeavenger07** [comment]
Thanks, having a friendly event at work and need the labels 👍

**Comment by MichaelWashburnJr** [comment]
Ah I see, I'll make sure I add them

**Pull request merged**
