### PR TITLE
Setup everything for calculation of OG, FG, SRM, IBU, ABV and ABW. Calculate and Display is done! Edit still TODO.

### PR DESCRIPTION
**Pull request by icyflame**
This will **always** recalculate the values after each time the user saves it.

Functionality yet to be implemented:

1. Calculation of IBU, SRM
2. Let users edit these values but change if the ingredients change (Still thinking about how to implement this. We could do something like have the values `recipe.old_og`, `recipe.old_fg` etc, and then, when user clicks on Save, we could calculate the new values of og, fg etc. If these match `old_og` and `old_fg`, but the present `recipe.og` and `recipe.fg` has been changed, then we know that the user has changed it manually. @mdw7326 Tell me if you like this approach.)

Demo:

image

### CODE REVIEW

**Comment by icyflame** [comment]
@mdw7326 I need a few things from you on this one:
1. Appropriate number of decimal points to show the percentages etc
2. Is the ABV and ABW returned as percentage? Tell me if I need to multiply it by 100 before displaying to the user.
3. The display of the OG, FG, SRM and IBU values. What are the values and units for each?

All these questions are because of my inexperience in homebrewing. :slightly_smiling_face: 

Sorry about my inactivity in the past couple weeks. Let's push OpenBrews towards 1.0 :smile:

**Comment by MichaelWashburnJr** [comment]
@icyflame This is awesome. Thanks. Here is the info you need:
1. On FG/OG: 3 decimals, ABV/ABW: 2, IBU: 0, SRM: 0
2. ABV and ABW is already multiplied by 100 (so it's in the range [0,100])
3. These values do have units, but are typically shown without them. OG/FG are densities, SRM is a number on a scale measuring color, and IBU is actually it's own unit (International Bitterness Units). Here's examples of each:
   - OG: 1.060
   - FG: 1.015
   - ABV: 6.00 %
   - ABW: 5.20 %
   - SRM: 28
   - IBU: 40

I think it is fine to show these as unit-less.

As for the question of when to calculate values, I think we should re-calculate each time one of it's dependencies change. Each value may or may not depend on other ingredients or values in the recipe. I'll make a list below of dependencies for each calculation.:
- OG: boilSize, boilSizeUnits, mashEfficiency, steepEfficiency, fermentables.ppg, fermentables.weight, fermentables.weightUnits
- FG: OG, yeasts.attenuation
- ABV: OG, FG, yeasts.alcoholTolerance (see note below)
- ABW: ABV
  -IBU/SRM: To be determined

The note I wanted to share about yeasts.alcoholTolerance is that it doesn't yet exist in the UI, but I have been using it in the BreweryDB service and RecipeUtils. I still need to add it to the UI. Please let me know you have any questions on here or on slack. This was much longer of a writeup than I indended

**Comment by icyflame** [comment]
@mdw7326 Okay. Thanks for the detailed comment! :smile: I have implemented the changes. No units made everything a lot simpler for me!

Coming back to the re-calculation thing, I understand your point about dependencies. But why don't we just re-calculate everything, at each save operation? It's only 5 calculations, and it's hardly anything that a modern browser / phone won't be able to handle without any noticeable lag (please correct me if I am wrong, I am unable to test using Ionic View because of an Internet Proxy server thing :frowning: ).

**Comment by MichaelWashburnJr** [comment]
@icyflame are you suggesting saving every time the save button is pressed? Because it would be nice to be able to see live updates as you change values. That's why I suggested the dependency thing. The few times I've built recipes, it's always been really useful to be able to change an amount of something and see how it reflects the calculated values

**Comment by icyflame** [comment]
@mdw7326 Didn't realise that live update was a thing. :+1: In the UI, where do you want to squeeze this new information in? (End of the recipe seems inconvenient)

**Comment by MichaelWashburnJr** [comment]
@icyflame I just finished the SRM and IBU calculations. I'll add dependencies for those here:

SRM:
- boilSize
- BoilSizeUnits
- fermentables.weight/weightUnts
- fermentables.srm

IBU:
- boilSize
- boilSizeInGallons
- OG
- hops.weight/weightUnits
- hops.aa
- hops.addTime

**Pull request merged**
