### PR TITLE
Possibility to delete recipes (resolves issue #36)

### PR DESCRIPTION
**Pull request by rmnblm**
This PR resolves issue #36.
I also think it’s about time to extract all localStorage relevant code to it’s own service that’s why I created a recipeStore which is injected where needed.

### CODE REVIEW

**Comment by icyflame** [comment]
Hey @rmnblm, thanks for this patch. It was time, indeed! I don't see your changes to use the `RecipeStore` inside the `ViewRecipeCtrl` controller. Please add that :)

**Comment by rmnblm** [comment]
@icyflame Done. The url now of each recipe is now `recipes/view/[uuid]`

**Comment by MichaelWashburnJr** [comment]
Bower won't install angular-uuid for me, anyone else have that problem?

**Comment by rmnblm** [comment]
@mdw7326 I just removed the angular-uuid dependency and added a `uuid()` function inside the store. If needed, this method can be extracted to it's own module in the future.

**Comment by icyflame** [comment]
@mdw7326 I didn't have the angular-uuid problem. Do you think it's a good idea to have a custom UUID generating function in the app? I think we should use angular-uuid. (cc @rmnblm )

**Comment by rmnblm** [comment]
@icyflame @mdw7326 Both issues/PRs I've solved yesterday had the need for a unique identifier, that's why it was necessary to find a quick solution even when it wasn't part of the issues. ☺️  

You have a few options here
- Use https://github.com/broofa/node-uuid and create your own wrapper around it
- Use the already built wrapper https://github.com/munkychop/angular-uuid
- Use the name of a brew as unique identifier so you have more human-readable URLs like `http://localhost/recipes/view/citra-pale-ale`
- Do something other, any ideas?

**Comment by MichaelWashburnJr** [comment]
It would be nice to use angular-uuid instead of the custom wrapper, but I did have trouble using it for some reason. I spent some time trying to get it to install. I ran 'npm install &&a bower install', and tried debugging for a while but had no luck. Maybe we should at least create an issue for this.

**Pull request merged**
